### ISSUE TITLE
Following instructions results in an error.

### ISSUE THREAD

**Issue by Muunsyr** [canonical-websites/tutorials.ubuntu.com#108] opened 2017-02-08 09:17 UTC
In 'Create your first snap', page 2, following the instructions results in the following:
`$ sudo snap install classic --edge --devmode`
`classic (edge) 16.04 from 'canonical' installed`
`$ sudo classic`
`(classic)foo@localhost:~$ sudo classic`
`Creating classic environment`
_snip_
`Processing triggers for libc-bin (2.23-0ubuntu5) ...`
`cp: cannot stat '/etc/writable/hostname': No such file or directory`
`$ sudo classic`
`sudo: unknown user: tim`
`sudo: unable to initialize policy plugin`
`$ sudo classic`
`mount: devpts is already mounted or /dev/pts busy`
`       devpts is already mounted on /dev/pts`
`sudo: unknown user: tim`
`sudo: unable to initialize policy plugin`

This was attempted on Ubuntu 16.04 LTS. The tutorial 'Basic snap usage' was completed with no issues.

**Comment by roxyd** [comment] 2017-02-14 16:35
I had a similar issue. I got the "unknown user" error and "unable to initialize policy plugin. so I removed the snap and re-installed, capturing the output.

Description:	Ubuntu 16.10
Release:	16.10

r0xy@r0xy-pc:~$ sudo snap remove classic
classic removed
r0xy@r0xy-pc:~$ sudo snap install classic --edge --devmode
classic (edge) 16.04 from 'canonical' installed
r0xy@r0xy-pc:~$ sudo classic
Creating classic environment
Parallel unsquashfs: Using 4 processors
10925 inodes (12088 blocks) to write

[=====================================================================/] 12088/12088 100%

created 8477 files
created 1425 directories
created 2359 symlinks
created 79 devices
created 0 fifos
(Reading database ... 12867 files and directories currently installed.)
Preparing to unpack .../archives/apt_1.2.18_amd64.deb ...
Unpacking apt (1.2.18) over (1.2.18) ...
Selecting previously unselected package locales.
Preparing to unpack .../locales_2.23-0ubuntu5_all.deb ...
Unpacking locales (2.23-0ubuntu5) ...
Setting up apt (1.2.18) ...
Setting up locales (2.23-0ubuntu5) ...
Generating locales (this might take a while)...
Generation complete.
Processing triggers for libc-bin (2.23-0ubuntu5) ...
cp: cannot stat '/etc/writable/hostname': No such file or directory


It turns out that when following the directions, I did not understand what "ubuntu core" was and I installed it on a classic system.
This bug is also related:
https://bugs.launchpad.net/snappy/+bug/1621666?comments=all

The documentation should be updated to make it clear that you either must install on core OR please include instructions for installing on classic.

I am going to install ubuntu core: https://developer.ubuntu.com/core/get-started/kvm

I will let you know if there are additional issues once I am in core but for that I think the documentation should at least clarify.

--Roxy

**Comment by WillMoggridge** [comment] 2017-02-24 15:48
Thanks for bringing this to our attention. I will pass this on to the tutorials team.

**Comment by didrocks** [comment] 2017-02-27 07:54
The issue is more a snapd side than a tutorial one. It seems some parts of the snapd is now failing. Mind opening the bug on https://bugs.launchpad.net/snappy/+filebug, with snap -version? Mention you are using the classic snap.

I'm closing this bug meanwhile as the tutorial documentation is still correct, just a new release of ubuntu core broke it without workaround.

**Comment by didrocks** [comment] 2017-02-27 07:54
@WillMoggridge: I don't have access to bug status, mind closing it?

**Comment by roxyd** [comment] 2017-02-27 15:48
Does this describe the bug properly @didrocks ? https://bugs.launchpad.net/snappy/+bug/1621666?comments=all

**Comment by didrocks** [comment] 2017-02-27 16:57
Exactly! Was already reported thus. I'll add a note that for now, it doesn't work on ubuntu desktop (the good news is that you can directly develop on desktop without the lxc container though). Thanks for digging around!

**Closed** 2017-09-19 09:32 UTC
Labels: Tutorials Content, Type: Bug

**Comment by chrislea** [comment] 2017-10-25 21:28
I know this bug is closed, but I've run into the same issue. I went through the basic tutorial on snap usage, then started the "Create your first snap" tutorial, and got the
```
cp: cannot stat '/etc/writable/hostname': No such file or directory
```
error. Can anybody tell me what I need to do in order to actually complete the tutorial? I tried removing the `core` snap but it won't let me.

**Comment by royki** [comment] 2018-02-04 23:59
Facing same issue. Is there any update how to avoid this ?
`cp: cannot stat '/etc/writable/hostname': No such file or directory`

And in another terminal 
`sudo: unknown user: croy
sudo: unable to initialize policy plugin
`
