### ISSUE TITLE
Error when trying to "./run"

### ISSUE THREAD

**Issue by erik78se** [canonical-websites/tutorials.ubuntu.com#881] opened 2018-11-10 12:31 UTC
I'm unable to get the tutorials site to get started. What am I doing wrong here?

`erik@juju-dev:~/tutorials.ubuntu.com$ ./run `
 
yarn run v1.3.2
$ echo 'To build site, please use build-all'
To build site, please use build-all
Done in 0.12s.
 
yarn run v1.3.2
$ npm-run-all 'serve-examples {@}' --
/bin/sh: 1: npm-run-all: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
erik@juju-dev:~/tutorials.ubuntu.com$ snap list
Name       Version     Rev   Tracking  Publisher   Notes
charm      2.4.4       254   stable    johnsca     classic
core       16-2.35.5   5742  stable    canonical✓  core
docker     18.06.1-ce  321   stable    docker-inc  -
juju       2.4.5       5740  stable    canonical✓  classic
lxd        3.6         9510  stable    canonical✓  -
snapcraft  2.43.1      1871  stable    canonical✓  classic
erik@juju-dev:~/tutorials.ubuntu.com$
```

**Comment by Lin-Buo-Ren** [comment] 2018-11-11 17:53
Hello, I have this problem as well, try `./run serve tutorials` instead.

**Comment by mitechie** [comment] 2018-11-12 14:00
@erik78se did ./run serve tutorials work for you?

**Comment by pmatulis** [comment] 2018-11-12 14:51
I reproduced this on Bionic. `./run` didn't work with any of the invocations.

**Comment by erik78se** [comment] 2018-11-13 15:42
> @erik78se did ./run serve tutorials work for you?

I haven't had the time to try.

**Comment by erik78se** [comment] 2018-11-13 15:43
I have multiple issues apart from this. For example, how to serve on a different IP than "localhost". Since I develop in a virtual environment, its needed, and needed to explain - since I won't be able to see the result once I manage to produce it.

**Comment by pmatulis** [comment] 2018-11-13 16:21
I did eventually get this stuff to work. It seems a little wobbly though. Just re-invoking the same commands shouldn't make it work, but it did.

Re remote aspect, you can use SSH local port forwarding. That's what I do. It does make a screenshot of a browser address field less ideal. There is a way around that as well if that's a concern (i.e. locally route a public IP to the forwarded port on the localhost).

**Comment by anthonydillon** [comment] 2018-11-13 17:31
@nottrobin do you know what could improve this? I can't reproduce it.

**Comment by pmatulis** [comment] 2018-11-13 20:20
The problem, for me anyway, has to do with root privileges being required to connect to Docker when it's installed as a snap.

This is what I did on a fresh Bionic cloud instance with user 'ubuntu':

```
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh
sudo adduser ubuntu docker
newgrp docker
git clone https://github.com/canonical-websites/tutorials.ubuntu.com.git
cd tutorials.ubuntu.com
./run
```

Thanks to @caldav for the [Docker script](https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-convenience-script) idea.

**Comment by nottrobin** [comment] 2018-12-17 17:37
@erik78se it looks to me like your yarn dependencies might not be installed correctly. Could you try `./run clean` followed by `./run` again, and let me know if it helps at all?

@pmatulis yes you do need Docker to be able to run without root. This usually requires you to add your user to the `docker` group, but may need extra steps with the snap version, I'm not sure. If you discover what's needed for the snap, I'm sure the docker snap project would appreciate a bug report. But this doesn't look like the same issue that @erik78se was having.

**Comment by nottrobin** [comment] 2018-12-17 17:41
> For example, how to serve on a different IP than "localhost"

Actually it already shouldn't care about the hostname. So if you just discover the IP address of your most machine (e.g. with `ip addr` or `ifconfig`) then you should just be able to point to `http://{your-ip-address}:8016`.

**Comment by nottrobin** [comment] 2018-12-17 17:54
I just submitted https://github.com/canonical-websites/tutorials.ubuntu.com/pull/900 which will hopefully help with the dependency management.

Once that's merged, it will hopefully mean that this will work for you @erik78se without you needing to run `./run clean` first. But for now, you might was well try `./run clean` anyway :smile:

**Closed** 2018-12-19 11:50 UTC
Labels: Priority: High
