### ISSUE TITLE
The back button doesn't work when landing on a tutorial from another website

### ISSUE THREAD

**Issue by caldav** [canonical-websites/tutorials.ubuntu.com#557] opened 2017-12-14 08:13 UTC
The back arrow at the top of tutorials doesn't do anything when coming from another website.

1. Go to [snapcraft.io](https://snapcraft.io/) or [www.ubuntu.com](https://www.ubuntu.com/download/desktop)
2. Click on a tutorial link
3. On the tutorial page, click on the back arrow in the header

### What should happen

The back button is intended to take you either to the page you are coming from, or to the home of tutorials.ubuntu.com.

### What happens

Nothing.

```
Uncaught DOMException: Failed to execute 'pushState' on 'History': 
A history state object with URL 'https://snapcraft.io/' cannot be created in 
a document with origin 'https://tutorials.ubuntu.com' and 
URL 'https://tutorials.ubuntu.com/tutorial/create-your-first-snap
```

The impact is huge, in addition to preventing navigation using this component, it prevents readers from discovering other tutorials on the homepage, according to GA, there is a massive drop in views of the homepage starting between Nov 14 and 16. 

I believe this was introduced in https://github.com/canonical-websites/tutorials.ubuntu.com/commit/47defc631d0a1f0d67e3314518ee894e09814019#diff-5f386031a2f4bbead803ecdb5d7df60b

Instead of fixing the current code, I'm suggesting we make the use of the backURL parameter entirely explicit and manual, and simplify this code with the following logic:

```
if backURL
   window.location.href = backURL
else
  window.location.href = '/'
```

This way, unless explicitely stated in the URL (eg. `https://tutorials.ubuntu.com/tutorial/create-your-first-snap?backURL=https://snapcraft.io`), the back button would always take readers back to the homepage.

We should also drop the empty `backURL` parameter currently present in the URL when navigating from the homepage to a tutorial.

**Comment by caldav** [comment] 2017-12-14 08:30
@frankiegranato @WillMoggridge thoughts?

**Comment by WillMoggridge** [comment] 2017-12-14 11:12
@caldav I think it is a good idea to make it much more of an explicit feature. I'm having a look at a good approach now.

**Comment by WillMoggridge** [comment] 2017-12-14 12:12
I created a PR related to this: https://github.com/canonical-websites/tutorials.ubuntu.com/pull/559
Let me know your thoughts on it, I think it should correct this problem. Also setting up the explicit behaviour you mentioned.

This PR doesn't remove the auto back button behaviour. I think I would happy to remove it but I am not sure if it would cause some unhappiness. To remove it, we should delete these lines:
https://github.com/canonical-websites/tutorials.ubuntu.com/blob/master/src/codelabs-page.html#L144-L148

I think we should at least whitelist the sites that this sets it for, rather than setting it for every site.

**Comment by caldav** [comment] 2017-12-15 08:54
@WillMoggridge afaict this is the first time the auto back button actually works, so it won't cause any unhappiness.

I would be tempted to remove it, to regain some homepage discoverability, and keep explicit backURL for when we need it (a whitelist is a great idea, but not urgent imho).

Having it explicit also helps people understand why the back button is behaving differently.

**Comment by WillMoggridge** [comment] 2017-12-15 11:49
Yeah, sounds good then. It does seem like unexpected behaviour in a variety of circumstances.

**Comment by caldav** [comment] 2017-12-15 12:43
Remaining work item: whitelist

**Comment by frankiegranato** [comment] 2018-01-12 14:21
I think this is a UX problem. The back arrow functions as intended but in some user journeys (such as from an external site) the arrow looks as if it should serve a different purpose. In my opinion, this is a 'won't fix' because it is part of a much larger issue - i.e. the navigation of the whole site.

**Closed** 2018-02-28 09:23 UTC
Labels: Priority: High, Type: Bug
